GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('enderium')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROTOR)
        .color(0x2CA9AE).secondaryColor(0x0B3056).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(2048, 4, 0)
        .blastTemp(2500, 1)
    event.create('signalum')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR)
        .color(0xEF3706).secondaryColor(0xA40E01).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(512, 4, 0)
        .blastTemp(1350, 0)
    event.create('stellar')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0xBAD4FF).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(8192, 4, 0)
    event.create('starmetal')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0x2B5AA8).iconSet(GTMaterialIconSet.SHINY)
    event.create('manasteel')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0x3D78DB).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(128, 4, 0)
    event.create('terrasteel')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0x31E52B).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(128, 4, 0)
    event.create('lumium')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR)
        .color(0xEAD489).iconSet(GTMaterialIconSet.SHINY)

    event.create('mana')
        .fluid()
        .color(0x439ADF)
    event.create('unstable_mana')
        .fluid()
        .color(0x439ADF)
    event.create('infused_nitro_fuel')
        .fluid()
        .color(0x09FFCD)
    event.create('potassium_chloride')
        .fluid()
        .color(0xA2C1BC)
    event.create('cryogenic_oxygen')
        .fluid()
        .color(0x4286F4)
    event.create('cryogenic_hydrogen')
        .fluid()
        .color(0xEDF1F7)
    event.create('naquadriatic_fuel')
        .fluid()
        .color(0x24022b)
})

GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('skystone')
        .color(0x303031).secondaryColor(0x3a4447).iconSet(GTMaterialIconSet.METALLIC)
        .flags(GTMaterialFlags.GENERATE_LENS)
})