GTCEuStartupEvents.registry('gtceu:material', event => {
    event.create('energetic_alloy')
        .ingot()
        .color(0xecbc3c).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(128, 4, 0)
    event.create('signalum')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR)
        .color(0xEF3706).secondaryColor(0xA40E01).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(512, 4, 0)
        .blastTemp(1350, 0)
    event.create('vibrant_alloy')
        .ingot()
        .color(0xe0ea6a).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(2048, 4, 0)
    event.create('enderium')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROTOR)
        .color(0x2CA9AE).secondaryColor(0x0B3056).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(8192, 4, 0)
        .blastTemp(2500, 1)
    event.create('stellar')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0xBAD4FF).iconSet(GTMaterialIconSet.SHINY)
        .cableProperties(32768, 4, 0)
     event.create('starmetal')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR, GTMaterialFlags.GENERATE_ROD)
        .color(0x2B5AA8).iconSet(GTMaterialIconSet.SHINY)
    event.create('lumium')
        .ingot()
        .flags(GTMaterialFlags.GENERATE_BOLT_SCREW, GTMaterialFlags.GENERATE_PLATE, GTMaterialFlags.GENERATE_GEAR)
        .color(0xEAD489).iconSet(GTMaterialIconSet.SHINY)
   

    event.create('mana')
        .fluid()
        .color(0x439ADF)
    event.create('unstable_mana')
        .fluid()
        .color(0x439ADF)
    event.create('infused_nitro_fuel')
        .fluid()
        .color(0x09FFCD)
    event.create('cryogenic_oxygen')
        .fluid()
        .color(0x4286F4)
    event.create('cryogenic_hydrogen')
        .fluid()
        .color(0xEDF1F7)
    event.create('naquadriatic_fuel')
        .fluid()
        .color(0x24022b)
})
