StartupEvents.registry('item', event => {

    function materialBuilder(material, hexColor){
      event.create(material + '_ore_clump').texture('kubejs:item/ore_clump').color(hexColor)
      event.create(material + '_ore_cluster').texture('kubejs:item/ore_cluster').color(hexColor)
      event.create(material + '_ore_crystal').texture('kubejs:item/ore_crystal').color(hexColor)
      event.create(material + '_ore_shard').texture('kubejs:item/ore_shard').color(hexColor)
    }

    materialBuilder('almandine', 0xa21717)
    materialBuilder('asbestos', 0xE6E6E6)
    materialBuilder('hematite', 0xff7161)
    materialBuilder('blue_topaz', 0xdbfeff)
    materialBuilder('goethite', 0x97873a)
    materialBuilder('calcite', 0xfffef8)
    materialBuilder('cassiterite', 0x89847e)
    materialBuilder('chalcopyrite', 0x96c185)
    materialBuilder('chromite', 0xc5c1a8)
    materialBuilder('cinnabar', 0xff335f)
    materialBuilder('coal', 0x393e41)
    materialBuilder('cobaltite', 0x1975ff)
    materialBuilder('cooperite', 0xe9ffa7)
    materialBuilder('diamond', 0xC8FFFF)
    materialBuilder('emerald', 0x17ff6c)
    materialBuilder('galena', 0x393e41)
    materialBuilder('garnierite', 0x32c880)
    materialBuilder('green_sapphire', 0x9ae6b0)
    materialBuilder('grossular', 0xffb777)
    materialBuilder('ilmenite', 0x2b2a24)
    materialBuilder('bauxite', 0xcfb853)
    materialBuilder('lazurite', 0x2836f1)
    materialBuilder('magnesite', 0xfbfbf6)
    materialBuilder('magnetite', 0xe3ddc3)
    materialBuilder('powellite', 0xd8cfac)
    materialBuilder('pyrite', 0xfffee6)
    materialBuilder('pyrolusite', 0xc7b5ab)
    materialBuilder('rock_salt', 0xd72310)
    materialBuilder('salt', 0xFAFAFA)
    materialBuilder('saltpeter', 0xE6E6E6)
    materialBuilder('sapphire', 0x3235e3)
    materialBuilder('scheelite', 0xd7e8b3)
    materialBuilder('sodalite', 0x3d54ff)
    materialBuilder('tantalite', 0x4e6b94)
    materialBuilder('spessartine', 0xffa81e)
    materialBuilder('sphalerite', 0xffdc88)
    materialBuilder('stibnite', 0x656565)
    materialBuilder('tetrahedrite', 0xa3a09b)
    materialBuilder('topaz', 0xe8d73a)
    materialBuilder('tungstate', 0xe0ffc4)
    materialBuilder('uraninite', 0xffd52e)
    materialBuilder('wulfenite', 0xff9000)
    materialBuilder('yellow_limonite', 0xf5e315)
    materialBuilder('nether_quartz', 0xf8efe3)
    materialBuilder('certus_quartz', 0xc2d6ff)
    materialBuilder('quartzite', 0xf2f5ed)
    materialBuilder('graphite', 0xa8a89e)
    materialBuilder('bornite', 0xffe05a)
    materialBuilder('chalcocite', 0x657882)
    materialBuilder('realgar', 0xff3d33)
    materialBuilder('bastnasite', 0xcaab60)
    materialBuilder('pentlandite', 0xe3cf13)
    materialBuilder('spodumene', 0xffbcbc)
    materialBuilder('lepidolite', 0xffdae4)
    materialBuilder('malachite', 0xecfeff)
    materialBuilder('barite', 0xe8e2d1)
    materialBuilder('alunite', 0xfbd677)
    materialBuilder('talc', 0xebffe9)
    materialBuilder('soapstone', 0x5a7261)
    materialBuilder('kyanite', 0xd5ffff)
    materialBuilder('pyrochlore', 0x5b4838)
    materialBuilder('oilsands', 0xe3c78a)
    materialBuilder('olivine', 0xa7e404)
    materialBuilder('opal', 0xf9e3ea)
    materialBuilder('amethyst', 0xcfa0f3)
    materialBuilder('lapis', 0x85a9ff)
    materialBuilder('apatite', 0x06cdf1)
    materialBuilder('tricalcium_phosphate', 0xfffddb)
    materialBuilder('red_garnet', 0x950c15)
    materialBuilder('yellow_garnet', 0xf6ff09)
    materialBuilder('vanadium_magnetite', 0x8a94a2)
    materialBuilder('pollucite', 0xeed9e1)
    materialBuilder('bentonite', 0xede8a3)
    materialBuilder('fullers_earth', 0xf3efbb)
    materialBuilder('pitchblende', 0xffd647)
    materialBuilder('monazite', 0xd0ee98)
    materialBuilder('trona', 0xe7e7b4)
    materialBuilder('gypsum', 0xfffaec)
    materialBuilder('zeolite', 0xf2e3e0)
    materialBuilder('redstone', 0xff0000)
    materialBuilder('electrotine', 0x83cbf5)
    materialBuilder('diatomite', 0xfffafa)
    materialBuilder('aluminium', 0xb6e5ff)
    materialBuilder('beryllium', 0x98d677)
    materialBuilder('cobalt', 0xf1e2d1)
    materialBuilder('copper', 0xe77c56)
    materialBuilder('gold', 0xfdf55f)
    materialBuilder('iron', 0xeeeeee)
    materialBuilder('lead', 0x7e6f82)
    materialBuilder('lithium', 0xd7e7ee)
    materialBuilder('molybdenum', 0xc1c1ce)
    materialBuilder('neodymium', 0x9a8b94)
    materialBuilder('nickel', 0xccdff5)
    materialBuilder('palladium', 0xA0A0A0)
    materialBuilder('platinum', 0xfff9da)
    materialBuilder('plutonium', 0xba2727)
    materialBuilder('silver', 0xDCDCFF)
    materialBuilder('sulfur', 0xfdff31)
    materialBuilder('thorium', 0x323528)
    materialBuilder('tin', 0xfafeff)
    materialBuilder('naquadah', 0x323232)
  })
  