ServerEvents.recipes(e => {

    e.remove({ output: 'minecraft:light_gray_bed' })
    e.remove({ output: 'minecraft:gray_bed' })
    e.remove({ output: 'minecraft:black_bed' })
    e.remove({ output: 'minecraft:brown_bed' })
    e.remove({ output: 'minecraft:orange_bed' })
    e.remove({ output: 'minecraft:yellow_bed' })
    e.remove({ output: 'minecraft:lime_bed' })
    e.remove({ output: 'minecraft:green_bed' })
    e.remove({ output: 'minecraft:cyan_bed' })
    e.remove({ output: 'minecraft:light_blue_bed' })
    e.remove({ output: 'minecraft:blue_bed' })
    e.remove({ output: 'minecraft:purple_bed' })
    e.remove({ output: 'minecraft:magenta_bed' })
    e.remove({ output: 'minecraft:pink_bed' })
    e.remove({ output: 'minecraft:red_bed' })
    e.remove({ output: 'supplimentares:bed_from_feather_block' })
    e.remove({ output: 'rats:trash_can' })
    e.remove({ output: 'minecraft:bamboo_raft' })
    e.remove({ id: 'enderio:stick' })
    e.remove({ id: 'minecraft:bone_meal' })
    e.remove({ id: 'aquaculture:iron_fishing_rod' })
    e.remove({ id: 'aquaculture:golden_fishing_rod' })
    e.remove({ id: 'aquaculture:diamond_fishing_rod' })
    e.remove({ id: 'aquaculture:neptunium_fishing_rod' })
})