#Maximum player movement speed (x^2 + y^2 + z^2) before triggering the moved too quickly messages. Vanilla is 100.0
#Range: 1.0 ~ 3.4028234663852886E38
max_player_speed = 1000.0
#Maximum player movement speed (x^2 + y^2 + z^2) before triggering the moved too quickly messages when Elytra flying. Vanilla is 300.0
#Range: 1.0 ~ 3.4028234663852886E38
max_player_elytra_speed = 3000.0
#Maximum player vehicle (ridden entity) movement speed (x^2 + y^2 + z^2) before triggering the moved too quickly messages. Vanilla is 100.0
#Range: 1.0 ~ 3.4028234663852886E38
max_player_vehicle_speed = 100.0

