recipesAdditions:
  a:
    # Whether to harden AE2WTLib recipes.
    # Default: true
    harderAE2WTLibRecipes: true

    # Whether to harden Alchemistry recipes.
    # Default: true
    harderAlchemistryRecipes: false

    # Whether to harden Applied Botanics recipes.
    # Default: true
    harderAppliedBotanicsRecipes: true

    # Whether to harden Applied Energistics 2 recipes.
    # Default: true
    harderAppliedEnergistics2Recipes: true

    # Whether to harden Applied Flux recipes.
    # Default: true
    harderAppliedFluxRecipes: true

    # Whether to harden Applied Mekanistics recipes.
    # Default: true
    harderAppliedMekanisticsRecipes: true

    # Whether to harden Ars Nouveau recipes.
    # Default: true
    harderArsNouveauRecipes: true

    # Whether to harden Ars …nergistique recipes.
    # Default: true
    harderArs…nergistiqueRecipes: true

    # Whether to harden Assembly Lines recipes.
    # Default: true
    harderAssemblyLinesRecipes: true

  b:
    # Whether to harden Ballistix recipes.
    # Default: true
    harderBallistixRecipes: false

    # Whether to harden Better Archeology recipes.
    # Default: true
    harderBetterArcheologyRecipes: false

    # Whether to harden Biomes O' Plenty recipes.
    # Default: true
    harderBiomesOPlentyRecipes: false

    # Whether to harden Blastcraft mod recipes.
    # Default: true
    harderBlastcraftModRecipes: false

    # Whether to harden Botania recipes.
    # Default: true
    harderBotaniaRecipes: false

  c:
    # Whether to harden CC Tweaked recipes.
    # Default: true
    harderCCTweakedRecipes: true

    # Whether to harden CC:C Bridge recipes.
    # Default: true
    harderCCCBridgeRecipes: false

    # Whether to harden Chem Lib recipes.
    # Default: true
    harderChemLibRecipes: false

    # Whether to harden Chisel and Bits recipes.
    # Default: true
    harderChiselAndBitsRecipes: true

    # Whether to harden Connected Glass recipes.
    # Default: true
    harderConnectedGlassRecipes: false

    # Whether to harden Cooking for Blockheads recipes.
    # Default: true
    harderCookingForBlockheadsRecipes: false

    # Whether to harden Create recipes.
    # Default: true
    harderCreateRecipes: false

  d:
    # Whether to harden Dank Storage recipes.
    # Default: true
    harderDankStorageRecipes: false

    # Whether to harden Domum Omamentum recipes.
    # Default: true
    harderDomumOmamentumRecipes: false

    # Whether to harden Dynamic Electricity recipes.
    # Default: true
    harderDynamicElectricityRecipes: false

  e:
    # Whether to harden Electrodynamics recipes.
    # Default: true
    harderElectrodynamicsRecipes: false

    # Whether to harden Ender Chest recipes.
    # Default: true
    harderEnderChestRecipes: false

    # Whether to harden Ender IO recipes.
    # Default: true
    harderEnderIORecipes: false

    # Whether to harden Ender Tanks recipes.
    # Default: true
    harderEnderTanksRecipes: false

    # Whether to harden Electrodynamics recipes.
    # Default: true
    harderExtraDisksRecipes: false

  f:
    # Whether to harden Flux Network recipes.
    # Default: true
    harderFluxNetworkRecipes: false

  g:
  h:
  i:
    # Whether to harden Industrial Foregoing recipes.
    # Default: true
    harderIndustrialForegoingRecipes: false

    # Whether to harden Iron Chest recipes.
    # Default: true
    harderIronChestRecipes: false

    # Whether to harden Iron Furnaces recipes.
    # Default: true
    harderIronFurnacesRecipes: false

    # Whether to harden Iron Jetpacks recipes.
    # Default: true
    harderIronJetpacksRecipes: false

    # Whether to harden Iron Shulker Box recipes.
    # Default: true
    harderIronShulkerBoxRecipes: false

  j:
    # Whether to harden Jumbo Furnace recipes.
    # Default: true
    harderJumboFurnaceRecipes: false

    # Whether to harden Just Stargate Mod recipes.
    # Default: true
    harderJustStargateModRecipes: false

  k:
  l:
  m:
    # Whether to harden ME Requester recipes.
    # Default: true
    harderMERequesterRecipes: false

    # Whether to harden MEGA Cells recipes.
    # Default: true
    harderMEGACellsRecipes: false

    # Whether to harden Mekanism recipes.
    # Default: true
    harderMekanismRecipes: false

    # Whether to harden Mekanism Additions recipes.
    # Default: true
    harderMekanismAdditionsRecipes: false

    # Whether to harden Mekanism Generators recipes.
    # Default: true
    harderMekanismGeneratorsRecipes: false

    # Whether to harden Mekanism Tools recipes.
    # Default: true
    harderMekanismToolsRecipes: false

    # Whether to harden Mekanism-MoreSolarPanels recipes.
    # Default: true
    harderMekanismMoreSolarPanelsRecipes: false

    # Whether to harden Mekanism: Weapons recipes.
    # Default: true
    harderMekanismWeaponsRecipes: false

    # Whether to harden MineColonies recipes.
    # Default: true
    harderMineColoniesRecipes: false

    # Whether to harden MineColonies for ComputerCraft recipes.
    # Default: true
    harderMineColoniesForComputerCraftRecipes: false

    # Whether to harden Modular Force Fields System recipes.
    # Default: true
    harderModularForceFieldsSystemRecipes: false

    # Whether to harden More Red recipes.
    # Default: true
    harderMoreRedRecipes: false

    # Whether to harden Multi-Piston recipes.
    # Default: true
    harderMultiPistonRecipes: false

  n:
    # Whether to harden Nuclear Science recipes.
    # Default: true
    harderNuclearScienceRecipes: false

  o:
  p:
    # Whether to harden Pipez recipes.
    # Default: true
    harderPipezRecipes: false

    # Whether to harden Powah recipes.
    # Default: true
    harderPowahRecipes: false

    # Whether to harden Productive Bees recipes.
    # Default: true
    harderProductiveBeesRecipes: true

  q:
  r:
    # Whether to harden Reborn Storage recipes.
    # Default: true
    harderRebornStorageRecipes: false

    # Whether to harden Rechiseled recipes.
    # Default: true
    harderRechiseledRecipes: true

    # Whether to harden Rechiseled Create recipes.
    # Default: true
    harderRechiseledCreateRecipes: true

    # Whether to harden Refined Cooking recipes.
    # Default: true
    harderRefinedCookingRecipes: false

    # Whether to harden Refined Storage recipes.
    # Default: true
    harderRefinedStorageRecipes: false

    # Whether to harden Refined Storage Addon recipes.
    # Default: true
    harderRefinedStorageAddonRecipes: false

    # Whether to harden Refined Storage Infinite Booster recipes.
    # Default: true
    harderRefinedStorageInfiniteBoosterRecipes: false

    # Whether to harden Refined Storage Insert Export Upgrade recipes.
    # Default: true
    harderRefinedStorageInsertExportUpgradeRecipes: false

    # Whether to harden Refined Storage Requestify recipes.
    # Default: true
    harderRefinedStorageRequestifyRecipes: false

  s:
    # Whether to harden Simple Light recipes.
    # Default: true
    harderSimpleLightRecipes: false

    # Whether to harden Specialised Cells recipes.
    # Default: true
    harderSpecialisedCellsRecipes: false

  t:
    # Whether to harden The Twilight Forest recipes.
    # Default: true
    harderTheTwilightForestRecipes: true

  u:
    # Whether to harden Universal Grid recipes.
    # Default: true
    harderUniversalGridRecipes: false

  v:
  w:
    # Whether to harden Wireless Chargers recipes.
    # Default: true
    harderWirelessChargersRecipes: false

  x:
  y:
  z:
recipesRemoval:
  a:
    # Whether to harden AE2WTLib recipes.
    # Default: true
    harderAE2WTLibRecipes: false

    # Whether to harden Alchemistry recipes.
    # Default: true
    harderAlchemistryRecipes: false

    # Whether to harden Applied Botanics recipes.
    # Default: true
    harderAppliedBotanicsRecipes: false

    # Whether to harden Applied Cooking recipes.
    # Default: true
    harderAppliedCookingRecipes: false

    # Whether to harden Applied Energistics 2 recipes.
    # Default: true
    harderAppliedEnergistics2Recipes: false

    # Whether to harden Applied Flux recipes.
    # Default: true
    harderAppliedFluxRecipes: false

    # Whether to harden Applied Mekanistics recipes.
    # Default: true
    harderAppliedMekanisticsRecipes: false

    # Whether to harden Ars Nouveau recipes.
    # Default: true
    harderArsNouveauRecipes: false

    # Whether to harden Ars …nergistique recipes.
    # Default: true
    harderArs…nergistiqueRecipes: false

    # Whether to harden Assembly Lines recipes.
    # Default: true
    harderAssemblyLinesRecipes: false

  b:
    # Whether to harden Ballistix recipes.
    # Default: true
    harderBallistixRecipes: false

    # Whether to harden Better Archeology recipes.
    # Default: true
    harderBetterArcheologyRecipes: false

    # Whether to harden Biomes O' Plenty recipes.
    # Default: true
    harderBiomesOPlentyRecipes: false

    # Whether to harden Blastcraft mod recipes.
    # Default: true
    harderBlastcraftModRecipes: false

    # Whether to harden Botania recipes.
    # Default: true
    harderBotaniaRecipes: false

  c:
    # Whether to harden CC Tweaked recipes.
    # Default: true
    harderCCTweakedRecipes: true

    # Whether to harden CC:C Bridge recipes.
    # Default: true
    harderCCCBridgeRecipes: false

    # Whether to harden Chem Lib recipes.
    # Default: true
    harderChemLibRecipes: false

    # Whether to harden Chisel and Bits recipes.
    # Default: true
    harderChiselAndBitsRecipes: true

    # Whether to harden Connected Glass recipes.
    # Default: true
    harderConnectedGlassRecipes: false

    # Whether to harden Cooking for Blockheads recipes.
    # Default: true
    harderCookingForBlockheadsRecipes: false

    # Whether to harden Create recipes.
    # Default: true
    harderCreateRecipes: false

  d:
    # Whether to harden Dank Storage recipes.
    # Default: true
    harderDankStorageRecipes: false

    # Whether to harden Domum Omamentum recipes.
    # Default: true
    harderDomumOmamentumRecipes: false

    # Whether to harden Dynamic Electricity recipes.
    # Default: true
    harderDynamicElectricityRecipes: false

  e:
    # Whether to harden Electrodynamics recipes.
    # Default: true
    harderElectrodynamicsRecipes: false

    # Whether to harden Ender Chest recipes.
    # Default: true
    harderEnderChestRecipes: false

    # Whether to harden Ender IO recipes.
    # Default: true
    harderEnderIORecipes: false

    # Whether to harden Ender Tanks recipes.
    # Default: true
    harderEnderTanksRecipes: false

    # Whether to harden Electrodynamics recipes.
    # Default: true
    harderExtraDisksRecipes: false

  f:
    # Whether to harden Flux Network recipes.
    # Default: true
    harderFluxNetworkRecipes: false

  g:
  h:
  i:
    # Whether to harden Industrial Foregoing recipes.
    # Default: true
    harderIndustrialForegoingRecipes: false

    # Whether to harden Iron Chest recipes.
    # Default: true
    harderIronChestRecipes: false

    # Whether to harden Iron Furnaces recipes.
    # Default: true
    harderIronFurnacesRecipes: false

    # Whether to harden Iron Jetpacks recipes.
    # Default: true
    harderIronJetpacksRecipes: false

    # Whether to harden Iron Shulker Box recipes.
    # Default: true
    harderIronShulkerBoxRecipes: false

  j:
    # Whether to harden Jumbo Furnace recipes.
    # Default: true
    harderJumboFurnaceRecipes: false

    # Whether to harden Just Stargate Mod recipes.
    # Default: true
    harderJustStargateModRecipes: false

  k:
  l:
  m:
    # Whether to harden ME Requester recipes.
    # Default: true
    harderMERequesterRecipes: false

    # Whether to harden MEGA Cells recipes.
    # Default: true
    harderMEGACellsRecipes: false

    # Whether to harden Mekanism recipes.
    # Default: true
    harderMekanismRecipes: false

    # Whether to harden Mekanism Removeitions recipes.
    # Default: true
    harderMekanismAdditionsRecipes: false

    # Whether to harden Mekanism Generators recipes.
    # Default: true
    harderMekanismGeneratorsRecipes: false

    # Whether to harden Mekanism Tools recipes.
    # Default: true
    harderMekanismToolsRecipes: false

    # Whether to harden Mekanism-MoreSolarPanels recipes.
    # Default: true
    harderMekanismMoreSolarPanelsRecipes: false

    # Whether to harden Mekanism: Weapons recipes.
    # Default: true
    harderMekanismWeaponsRecipes: false

    # Whether to harden MineColonies recipes.
    # Default: true
    harderMineColoniesRecipes: false

    # Whether to harden MineColonies for ComputerCraft recipes.
    # Default: true
    harderMineColoniesForComputerCraftRecipes: false

    # Whether to harden Modular Force Fields System recipes.
    # Default: true
    harderModularForceFieldsSystemRecipes: false

    # Whether to harden More Red recipes.
    # Default: true
    harderMoreRedRecipes: false

    # Whether to harden Multi-Piston recipes.
    # Default: true
    harderMultiPistonRecipes: false

  n:
    # Whether to harden Nuclear Science recipes.
    # Default: true
    harderNuclearScienceRecipes: false

  o:
  p:
    # Whether to harden Pipez recipes.
    # Default: true
    harderPipezRecipes: false

    # Whether to harden Powah recipes.
    # Default: true
    harderPowahRecipes: false

    # Whether to harden Productive Bees recipes.
    # Default: true
    harderProductiveBeesRecipes: true

  q:
  r:
    # Whether to harden Reborn Storage recipes.
    # Default: true
    harderRebornStorageRecipes: false

    # Whether to harden Rechiseled recipes.
    # Default: true
    harderRechiseledRecipes: false

    # Whether to harden Rechiseled Create recipes.
    # Default: true
    harderRechiseledCreateRecipes: false

    # Whether to harden Refined Cooking recipes.
    # Default: true
    harderRefinedCookingRecipes: false

    # Whether to harden Refined Storage recipes.
    # Default: true
    harderRefinedStorageRecipes: false

    # Whether to harden Refined Storage Removeon recipes.
    # Default: true
    harderRefinedStorageAddonRecipes: false

    # Whether to harden Refined Storage Infinite Booster recipes.
    # Default: true
    harderRefinedStorageInfiniteBoosterRecipes: false

    # Whether to harden Refined Storage Insert Export Upgrade recipes.
    # Default: true
    harderRefinedStorageInsertExportUpgradeRecipes: false

    # Whether to harden Refined Storage Requestify recipes.
    # Default: true
    harderRefinedStorageRequestifyRecipes: false

  s:
    # Whether to harden Simple Light recipes.
    # Default: true
    harderSimpleLightRecipes: false

    # Whether to harden Specialised Cells recipes.
    # Default: true
    harderSpecialisedCellsRecipes: false

  t:
    # Whether to harden The Twilight Forest recipes.
    # Default: true
    harderTheTwilightForestRecipes: true

  u:
    # Whether to harden Universal Grid recipes.
    # Default: true
    harderUniversalGridRecipes: false

  v:
  w:
    # Whether to harden Wireless Chargers recipes.
    # Default: true
    harderWirelessChargersRecipes: false

  x:
  y:
  z:
